### ISSUE TITLE
The env_stego_gan.yml file could not be found.

### ISSUE THREAD

**Issue by Luhui-Zhao** [sian-wusidi/StegoGAN#1]
Hello, I am very interested in your work. However, when I was creating the environment required by the project, I did not find the env_stego_gan.yml file you provided. I hope to seek your help, thank you.
![82e51b0307420908fe7e9dd0e348630a](https://github.com/user-attachments/assets/08c23e27-abbe-4025-8d70-0617a308348e)

**Comment by sian-wusidi** [comment]
we have just uploaded the yml
